# Generated by Django 5.0.2 on 2024-02-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('gitlink', models.URLField(blank=True)),
                ('projectlink', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
